#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "以PUID=${PUID}，PGID=${PGID}的身份启动程序..."

groupmod -o -g "$PGID" ms
usermod -o -u "$PUID" ms

chown -R ms:ms "${WORKDIR}" "${HOME}" /config /usr/lib/chromium /etc/hosts